### PR TITLE
Remove Rails.root part from error_source and add release a separate field

### PR DESCRIPTION
**Pull request by davidsevcik**

### CODE REVIEW

**Comment by lpil** [comment]
Specs?

**Comment by davidsevcik** [comment]
Yeah, will do it. I just wanted to quickly put down some code before I forget about it.

**Comment by jonnyarnold** [comment]
Where are we with specs for this?

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by lpil** [comment]
ping @davidsevcik

**Pull request closed without merging**
